// Generated by tools/build_hero_frames.py — do not edit by hand.
export const HERO_SEQUENCE = {
  count: 150,
  width: 1280,
  height: 720,
  srcFor: (i: number) => `/hero/f_${String(i).padStart(4, "0")}.webp`,
} as const;
